name: Main

on:
  push:
    branches: [ main, release/*, feature/githubActions]
  pull_request:

jobs:
  Build:
    runs-on: macos-11
    env:
      workspace: "Hyperspace.xcworkspace"
    strategy:
      fail-fast: false
      matrix:
        name: ["iOS", "tvOS", "watchOS"]
        include:
            - name: "iOS"
              scheme: "Hyperspace_iOS"
              destination: "platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro"
              test: true
              lint: true

            - name: "tvOS"
              scheme: "Hyperspace_tvOS"
              destination: "platform=tvOS Simulator,OS=15.0,name=Apple TV 4K"
              test: true
              lint: true

            - name: "watchOS"
              scheme: "Hyperspace_watchOS"
              destination: "platform=watchOS Simulator,OS=8.0,name=Apple Watch Series 6 - 44mm"
              test: false
              lint: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test
      run: >
        if [[ ${{ matrix.test }} == true ]]; then
          xcodebuild test \
            -workspace ${{ env.workspace }} \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES || exit 1
        else
          xcodebuild \
            -workspace ${{ env.workspace }} \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO || exit 1
        fi

    - name: Lint
      run: >
        if [[ ${{ matrix.lint }} == true ]]; then
          pod lib lint
        fi
