name: Main

on:
  push:
    branches: [ main, release/*]
  pull_request:

jobs:
  Build:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
      workspace: "Hyperspace.xcworkspace"
    strategy:
      fail-fast: false
      matrix:
        name: ["iOS", "tvOS", "watchOS", "macOS"]
        include:
            - name: "iOS"
              scheme: "Hyperspace iOS"
              destination: "platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro"
              test: true

            - name: "tvOS"
              scheme: "Hyperspace tvOS"
              destination: "platform=tvOS Simulator,OS=15.2,name=Apple TV 4K"
              test: true

            - name: "watchOS"
              scheme: "Hyperspace watchOS"
              destination: "platform=watchOS Simulator,OS=8.3,name=Apple Watch Series 6 - 44mm"
              test: true

            - name: "macOS"
              scheme: "Hyperspace macOS"
              destination: "arch=x86_64"
              test: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test
      run: >
        if [[ ${{ matrix.test }} == true ]]; then
          xcodebuild test \
            -workspace ${{ env.workspace }} \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES || exit 1
        else
          xcodebuild \
            -workspace ${{ env.workspace }} \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO || exit 1
        fi

  Lint:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
      cocoapods: true
      spm: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      run: >
        if [[ ${{ env.spm }} == true ]]; then
          swift package describe
        fi

        if [[ ${{ env.cocoapods }} == true ]]; then
          pod lib lint
        fi
